# Generated by Django 5.2.5 on 2026-10-01 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_bio_profile_first_name_profile_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
