# Generated by Django 6.1.1 on 2026-10-05 06:48
from django.db import migrations

from users.constants import DEFAULT_USER_GROUPS


def create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for group_name, permissions in DEFAULT_USER_GROUPS.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        db_permissions = list(
                Permission.objects.filter(
                codename__in=permissions
            )
        )
        group.permissions.set(db_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.RunPython(create_default_groups, migrations.RunPython.noop),
    ]
