# Generated by Django 5.2.5 on 2026-10-01 07:42

from django.db import migrations


def seed_messages(apps, schema_editor):
    import faker

    Message = apps.get_model("messenger", "Message")

    fake = faker.Faker()

    messages = [Message(text=fake.sentence()) for _ in range(100)]
    Message.objects.bulk_create(messages)


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_messages, migrations.RunPython.noop),
    ]
